package com.voluble.titanMC.regions.protection.model;

public enum ProtectionAction {
	BLOCK_BREAK,
	BLOCK_PLACE,
	BLOCK_INTERACT,
	PHYSICAL_INTERACT,
	CONTAINER_OPEN,
	ENTITY_PLACE,
	ENTITY_INTERACT,
	ENTITY_DAMAGE,
	HANGING_MODIFY,
	BUCKET_FILL,
	BUCKET_EMPTY,
	EXPLOSION_BLOCK_DAMAGE,
	PISTON_MOVE,
	FLUID_FLOW,
	FIRE_SPREAD,
	VEHICLE_PLACE,
	VEHICLE_ENTER,
	VEHICLE_MODIFY
}
