package com.voluble.titanMC.milestones.model;

public enum MilestoneMetric {
	MINE_BLOCKS_BROKEN,
	MINE_BLOCKS_IN_MINE,
	DONATOR_TOOL_USED,
	MINE_BLOCKS_AFTER_RESET,
	MINE_RESET_PARTICIPATION,
	RANK_REACHED,
	WARD_REACHED,
	PRESTIGE_REACHED
}
